setup.cfg, src/pytest_servers/azure.py, src/pytest_servers/exceptions.py, src/pytest_servers/factory.py, src/pytest_servers/fixtures.py, src/pytest_servers/s3.py, src/pytest_servers/utils.py, tests/test_factory.py, tests/test_utils.py
This is accomplished through the `azurite` fixture, which spins up azurite in a docker container and returns the connection string.
Mocking Azure (with azurite) requires `docker-py`, which might fail on windows. `docker-py` might be swapped for `pytest-docker` or some other mechanism in the near future.
=> Add azure support

src/pytest_servers/fixtures.py, src/pytest_servers/s3.py
Using `0` as default port for moto chooses a random port. This also gets rid of the `--moto-port` pytest argument
=> s3: make moto use a random port by default

.github/workflows/tests.yml, setup.cfg
use `continue-on-error` for linting/testing on 3.11.
`universal_pathlib` currently has no 3.11 support, and `fsspec` has spotty support for 3.11 (for example `pip install s3fs` fails due to an `aiohttp` build error).
=> ci: ignore errors on 3.11

src/pytest_servers/factory.py, tests/test_memory.py
When creating an UPath instance with a "memory://" scheme, the first part of the URL (netloc) is ignored by universal pathlib's `MemoryPath`, resulting in all temporary directories pointing to the same location, the root of `MemoryFileSystem`
=> factory: fix memory path usage

src/pytest_servers/local.py
Makes paths returned by `tmp_upath_factory` more consistent.
=> local: add path attribute to LocalFileSystem

src/pytest_servers/utils.py
[`docker-py`](https://github.com/docker/docker-py) uses the deprecated `distutils` module, which results in `DeprecationWarnings` being caught by `pytest` whenever using the `docker_client` fixtures. As a temporary workaround, we just catch the warnings, waiting for either `docker-py` to fix the issue or to remove it entirely
=> utils: catch docker-py deprecation warnings

setup.cfg, src/pytest_servers/azure.py, src/pytest_servers/factory.py, src/pytest_servers/fixtures.py, src/pytest_servers/gcs.py, src/pytest_servers/s3.py
lazily request fixture values in `_mock_remote_setup` so that containers/processes are only started when actually requesting a temporary dir on the given mock remote.
=> factory: make fixtures lazy

.github/workflows/tests.yml
It's a bit nicer to look at, and selects session directly without using env. Also this will work for any future python versions.
Similar changes were made across different repositories.
=> Simplify workflow file for 3.11 Python

.github/workflows/tests.yml, noxfile.py, setup.cfg
Pytest loads the plugin before the test is run, so we have to start coverage before pytest loads.
See https://github.com/iterative/pytest-servers/runs/7918315266?check_suite_focus=true#step:6:32.
=> run tests with coverage for correct coverage reporting

pyproject.toml, setup.cfg, src/pytest_servers/azure.py, src/pytest_servers/gcs.py, src/pytest_servers/s3.py, src/pytest_servers/utils.py
adds support for `pytest-xdist` (or other pytest parallel executors) by making sure that only one of the session-scoped fixtures that spawn docker containers actually spawn new containers.
Note that for now we still might spawn multiple `moto` processes when requesting the the `s3_server_fixture`.
=> add support for pytest-xdist

renovate.json, src/pytest_servers/azure.py, src/pytest_servers/gcs.py
used to keep docker tags for azurite and fake-gcs-server fixtures up-to-date
closes #56
=> Add renovate

setup.cfg, src/pytest_servers/s3.py
* filelock is actually a mandatory dependency
* Until the freshly released moto 4.0.8, the emulation of `list_object_versions` was buggy
* Flask 2.2+ changed the startup message of the moto server
=> Fix some dependency issues

noxfile.py, pyproject.toml, setup.cfg
Was broken after we started using xdist: https://github.com/iterative/pytest-servers/pull/52.
=> fix coverage

.pre-commit-config.yaml, pyproject.toml, src/pytest_servers/s3.py, src/pytest_servers/utils.py
See https://github.com/PyCQA/bandit.
=> add bandit, a security linter

src/pytest_servers/s3.py
#90 made `moto` a required dependency. Make the import lazy in order to avoid failures when the `[s3]` extra is not installed
=> s3: make moto import lazy

README.rst, src/pytest_servers/factory.py, src/pytest_servers/fixtures.py, src/pytest_servers/s3.py, src/pytest_servers/utils.py, tests/test_factory.py, tests/test_fixtures.py, tests/test_utils.py
Current usage looks something like this:
```python
def test_on_versioned_s3(tmp_s3_path, versioning):
assert tmp_s3_path.fs.version_aware
...
def test_versioning_generic(tmp_upath_factory):
tmp_versioned_path = tmp_upath_factory.mktemp("s3", version_aware=True)
assert tmp_versioned_path.fs.version_aware
``` 
Only `gcs` and `s3` are currently supported.
=> versioning support

src/pytest_servers/s3.py
This avoids IPv6 resolution failures which can cause a massive slow-down on Windows.
Workaround for #105
=> Force IPv4 resolution on Windows for MockedS3Server

src/pytest_servers/factory.py
To actually get an error instead of a false-positive "Container exists" if we encouter an error during container creation  https://github.com/fsspec/adlfs/pull/415
=> azure: use assume_container_exists=False

.github/workflows/tests.yml, src/pytest_servers/factory.py
MacOS images now come with colima installed https://github.com/actions/runner-images/issues/2150
Related https://github.com/iterative/dvc-azure/issues/67
Related https://github.com/iterative/dvc-gs/issues/43
=> factory: don't skip MacOS on CI

.github/workflows/tests.yml
Windows/MacOS jobs are taking longer than 15m, making CI fail
=> gha: increase timeout to 30m

setup.cfg
installing `moto[server]` causes pip backtracking for `botocore`, explicitly define and pin it to speed up installs.
=> deps: explicitly define botocore to avoid pip backtracking

README.rst, src/pytest_servers/factory.py, src/pytest_servers/fixtures.py, src/pytest_servers/s3.py, tests/test_fixtures.py, tests/test_utils.py
By passing `client_kwargs` to the `s3` temp upath factory, we can avoid having to monkeypatch s3 environment variable for the whole test session.
=> fixtures: remove s3_fake_creds_file, allow for finer boto3 client configuration

.github/workflows/tests.yml
Due to [the current state of colima](https://github.com/iterative/pytest-servers/issues/142#issuecomment-1906041439), CI on MacOS is unreliable
=> gha: ignore failures on MacOS

.github/workflows/tests.yml, noxfile.py, pyproject.toml, src/pytest_servers/factory.py, tests/test_factory.py
Testing for https://github.com/fsspec/universal_pathlib/pull/173.
=> add support for 3.12

src/pytest_servers/factory.py, src/pytest_servers/fixtures.py
Closes https://github.com/iterative/pytest-servers/issues/157; to be released as <kbd>v0.5.1</kbd>
=> Fix `tmp_path_factory` usage

src/pytest_servers/factory.py, src/pytest_servers/fixtures.py
This pull request turns #158 into a "breaking" change. If someone starts using `TempUPathFactory.from_request` without `tmp_path_factory` we'll regret it. It's better to deprecate the old function signature as soon as possible.
This is a low-priority follow-up and we can discuss calmly whether it's a good idea or not. 🐢
=> Make `TempUPathFactory.from_request(tmp_path_factory)` mandatory

.github/workflows/tests.yml, src/pytest_servers/azure.py, src/pytest_servers/gcs.py
The pipeline is failing in `dvcx` because the tests depend on this repo and we haven't updated the required dependencies.
~In this PR I have downgraded the `macos` runners to `macos-13` as `macos-14` aka `macos-latest` does not currently support Docker.~
Used the same approach as in `dvcx`
I have also pulled in the image updates from #168 as they are required to make the tests pass and will be needed by `dvcx`.
[Example of failing dependency pipeline](https://github.com/iterative/dvcx/actions/runs/9011591378/job/24759445901).
See [here](https://iterativeai.slack.com/archives/C04A9RWEZBN/p1715223019757329) for more context.
=> Combine image updates with colima installation

README.rst, src/pytest_servers/factory.py, src/pytest_servers/fixtures.py, tests/test_factory.py
The commit extends pytest_servers to recognize 'gs' as an alias for 'gcs'. This allows users to use 'gs' as a parameter in pytest. Corresponding test cases have also been updated to reflect this change.
=> Add support for 'gs' as alias for 'gcs' in pytest servers

src/pytest_servers/gcs.py
Fixes access to signed URLs, objects, etc (everything that requires usually `storage.googleapis.com`).
=> fix(gcs): use host name (not url) for public host
